insert into app_user(name,username,password) values ('Samraj Timmapuram','parent','parent');
insert into app_user(name,username,password) values ('Sudhakar KR','child','child');

insert into app_user_roles(app_user_id,roles) values (1,'PARENT');
insert into app_user_roles(app_user_id,roles) values (1,'CHILD');
insert into app_user_roles(app_user_id,roles) values (2,'CHILD');

INSERT INTO USER_ROLES(NAME,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES('PARENT','Ravi','2017-01-01',NULL,NULL);
INSERT INTO USER_ROLES(NAME,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES('CHILD','Ravi','2017-01-01',NULL,NULL);
 
INSERT INTO USER_DETAILS(USER_NAME,PASSWORD,LAST_NAME,ROLE_ID,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES('vreswar','#kris123',null,'1','ravi','2017-08-08',null,null);
INSERT INTO USER_ROLES(NAME,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES('PARENT','ravi','2017-08-08',NULL,NULL);

INSERT INTO USER_PROFILE(TITLE,FIRST_NAME,LAST_NAME,USER_ID,DATE_OF_BIRTH,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,COUNTRY_CODE,ROLE_ID,POST_CODE,MOBILE_NUMBER,PARENT_ID,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES('MR.','Ravi','Varanasi',1,'2017-01-01','address line 1','address line 2', 'Bengaluru','IN',1,'560099','9999999999',null,'Ravi','2017-01-01',null,null);
INSERT INTO USER_PROFILE(TITLE,FIRST_NAME,LAST_NAME,USER_ID,DATE_OF_BIRTH,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,COUNTRY_CODE,ROLE_ID,POST_CODE,MOBILE_NUMBER,PARENT_ID,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES('MR.','Kiddo','Varanasi',1,'2018-01-01','address line 1','address line 2', 'Bengaluru','IN',1,'560099','9999999998',null,'Ravi','2017-01-01',null,null);

INSERT INTO USER_ACCOUNT_SUMMARY(USER_ID,ROLE_ID,TITLE,ACCOUNT_TYPE,ACCOUNT_NUMBER,BALANCE,CURRENCY_CODE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES(1,1,'MR.','Savings','1234567890',10000000,'INR','Ravi','2017-01-01',null,null);

INSERT INTO USER_TRANSACTIONS(ACCOUNT_NUMBER,TRANSACTION_TYPE,TRANSACTION_SHORT_FORM,TRANSACTION_DETAIL,TRANSACTION_DATE,TRANSACTION_AMOUNT,IS_DEBIT) VALUES('1234567890','DEBIT','DEBIT TXN','TXN REFERENCE NO 12345-ONLINE-DEBIT','2017-01-01 07:18:00',34334,'YES');