CREATE TABLE `ING`.`USER_DETAILS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `ROLE_ID` VARCHAR(45) NULL,
  `CREATED_BY` VARCHAR(45) NULL,
  `CREATED_DATE` DATE NULL,
  `UPDATED_BY` VARCHAR(45) NULL,
  `UPDATED_DATE` DATE NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `USER_ROLES` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) DEFAULT NULL,
  `CREATED_BY` VARCHAR(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
   PRIMARY KEY (`ID`),
) ENGINE=InnoDB DEFAULT CHARSET=tis620;

CREATE TABLE `USER_PROFILE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(45) DEFAULT NULL,
  `FIRST_NAME` varchar(45) DEFAULT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  `USER_ID` INT NOT NULL,
  `DATE_OF_BIRTH` DATE NOT NULL,
  `ADDRESS_LINE_1` varchar(45) DEFAULT NULL,
  `ADDRESS_LINE_2` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `COUNTRY_CODE` varchar(45) NOT NULL,
  `ROLE_ID` INT NOT NULL,
  `POST_CODE` varchar(45) DEFAULT NULL,
  `MOBILE_NUMBER` varchar(45) DEFAULT NULL,
  `BSN` VARCHAR(45) DEFAULT NULL,
  `SHORT_NAME` VARCHAR(45) DEFAULT NULL,
  `PARENT_ID` INT NOT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
   PRIMARY KEY (`ID`),
   KEY `FORGNKY_idx3` (`USER_ID`),
   KEY `FORGNKY_idx4` (`ROLE_ID`),
   CONSTRAINT `FORGNKY_PROFILE_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER_DETAILS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT `FORGNKY_PROFILE_ROLE` FOREIGN KEY (`USER_ID`) REFERENCES `USER_DETAILS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=tis620;

CREATE TABLE `USER_ACCOUNT_SUMMARY` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `ROLE_ID` INT NOT NULL,
  `TITLE` varchar(45) DEFAULT NULL,
  `ACCOUNT_TYPE` varchar(45) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  `BALANCE` INT NOT NULL,
  `CURRENCY_CODE` varchar(45) NOT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
   PRIMARY KEY (`ID`),
   KEY `FORGNKY_idx5` (`USER_ID`),
   KEY `FORGNKY_idx6` (`ROLE_ID`),
   CONSTRAINT `FORGNKY_SUMMARY_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER_DETAILS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT `FORGNKY_SUMMARY_ROLE` FOREIGN KEY (`USER_ID`) REFERENCES `USER_DETAILS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=tis620;


CREATE TABLE `USER_TRANSACTIONS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_NUMBER` VARCHAR(45) NOT NULL,
  `TRANSACTION_TYPE` VARCHAR(45) NOT NULL,
  `TRAANSACTION_SHORT_FORM` varchar(45) DEFAULT NULL,
  `TRANSACTION_DETAIL` varchar(45) DEFAULT NULL,
  `TRANSACTION_DATE` DATETIME DEFAULT NULL,
  `TRANSACTION_AMOUNT` INT NOT NULL,
  `IS_DEBIT` varchar(10) NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=tis620;

